import { Menu } from "@/types";

// This file is auto-generated. Do not edit directly.
// @see https://raw.githubusercontent.com/ryohidaka/torikizoku-menus/main/dist/torikizoku.json
export const MENUS: Menu[] = [
  {
    id: 101,
    name: "もも貴族焼(たれ)",
    category: "貴族焼",
    imageUrl:
      "https://torikizoku.co.jp/assets/uploads/2024/03/momo_kizokuyaki_tare.jpg",
    calories: 231,
    salt: 1.9,
    isDrink: false,
    isAlcohol: false,
  },
  {
    id: 102,
    name: "もも貴族焼(塩)",
    category: "貴族焼",
    imageUrl:
      "https://torikizoku.co.jp/assets/uploads/2024/03/momo_kizokuyaki_shio.jpg",
    calories: 208,
    salt: 1.8,
    isDrink: false,
    isAlcohol: false,
  },
  {
    id: 103,
    name: "もも貴族焼(スパイス)",
    category: "貴族焼",
    imageUrl:
      "https://torikizoku.co.jp/assets/uploads/2024/03/momo_kizokuyaki_spice.jpg",
    calories: 215,
    salt: 4.5,
    isDrink: false,
    isAlcohol: false,
  },
  {
    id: 104,
    name: "むね貴族焼(たれ)",
    category: "貴族焼",
    imageUrl:
      "https://torikizoku.co.jp/assets/uploads/2024/03/mune_kizokuyaki_tare.jpg",
    calories: 165,
    salt: 1.5,
    isDrink: false,
    isAlcohol: false,
  },
  {
    id: 105,
    name: "むね貴族焼(塩)",
    category: "貴族焼",
    imageUrl:
      "https://torikizoku.co.jp/assets/uploads/2024/03/mune_kizokuyaki_shio.jpg",
    calories: 146,
    salt: 1.7,
    isDrink: false,
    isAlcohol: false,
  },
  {
    id: 106,
    name: "むね貴族焼(スパイス)",
    category: "貴族焼",
    imageUrl:
      "https://torikizoku.co.jp/assets/uploads/2024/03/mune_kizokuyaki_spice.jpg",
    calories: 152,
    salt: 4.3,
    isDrink: false,
    isAlcohol: false,
  },
  {
    id: 201,
    name: "ちからこぶ塩",
    category: "塩焼",
    imageUrl:
      "https://torikizoku.co.jp/assets/uploads/2023/05/shio_chikarakobu.jpg",
    calories: 125,
    salt: 0.9,
    isDrink: false,
    isAlcohol: false,
  },
  {
    id: 202,
    name: "手羽先塩",
    category: "塩焼",
    imageUrl:
      "https://torikizoku.co.jp/assets/uploads/2023/05/shio_tebasaki.jpg",
    calories: 253,
    salt: 0.9,
    isDrink: false,
    isAlcohol: false,
  },
  {
    id: 203,
    name: "三角（ぼんじり）",
    category: "塩焼",
    imageUrl:
      "https://torikizoku.co.jp/assets/uploads/2023/05/shio_sankaku.jpg",
    calories: 219,
    salt: 1.1,
    isDrink: false,
    isAlcohol: false,
  },
  {
    id: 204,
    name: "つくね塩",
    category: "塩焼",
    imageUrl:
      "https://torikizoku.co.jp/assets/uploads/2023/05/shio_tsukune.jpg",
    calories: 152,
    salt: 1.1,
    isDrink: false,
    isAlcohol: false,
  },
  {
    id: 205,
    name: "ささみ塩焼 -わさび粗おろし添え-",
    category: "塩焼",
    imageUrl: "https://torikizoku.co.jp/assets/uploads/2023/05/shio_sasami.jpg",
    calories: 75,
    salt: 0.7,
    isDrink: false,
    isAlcohol: false,
  },
  {
    id: 206,
    name: "ハート（ハツ）塩",
    category: "塩焼",
    imageUrl: "https://torikizoku.co.jp/assets/uploads/2023/05/shio_heart.jpg",
    calories: 105,
    salt: 0.5,
    isDrink: false,
    isAlcohol: false,
  },
  {
    id: 207,
    name: "砂ずり（砂肝）",
    category: "塩焼",
    imageUrl:
      "https://torikizoku.co.jp/assets/uploads/2023/05/shio_sunazuri.jpg",
    calories: 49,
    salt: 0.6,
    isDrink: false,
    isAlcohol: false,
  },
  {
    id: 208,
    name: "かわ塩",
    category: "塩焼",
    imageUrl: "https://torikizoku.co.jp/assets/uploads/2023/05/shio_kawa.jpg",
    calories: 356,
    salt: 2.1,
    isDrink: false,
    isAlcohol: false,
  },
  {
    id: 209,
    name: "やげんなんこつ",
    category: "塩焼",
    imageUrl: "https://torikizoku.co.jp/assets/uploads/2023/05/shio_yagen.jpg",
    calories: 95,
    salt: 1.2,
    isDrink: false,
    isAlcohol: false,
  },
  {
    id: 210,
    name: "ひざなんこつ",
    category: "塩焼",
    imageUrl:
      "https://torikizoku.co.jp/assets/uploads/2023/05/shio_nankotsu.jpg",
    calories: 27,
    salt: 1.2,
    isDrink: false,
    isAlcohol: false,
  },
  {
    id: 211,
    name: "せせり",
    category: "塩焼",
    imageUrl: "https://torikizoku.co.jp/assets/uploads/2023/05/shio_seseri.jpg",
    calories: 170,
    salt: 0.6,
    isDrink: false,
    isAlcohol: false,
  },
  {
    id: 301,
    name: "ちからこぶたれ",
    category: "たれ焼",
    imageUrl:
      "https://torikizoku.co.jp/assets/uploads/2023/05/tare_chikarakobu.jpg",
    calories: 141,
    salt: 0.9,
    isDrink: false,
    isAlcohol: false,
  },
  {
    id: 302,
    name: "手羽先たれ",
    category: "たれ焼",
    imageUrl:
      "https://torikizoku.co.jp/assets/uploads/2023/05/tare_tebasaki.jpg",
    calories: 270,
    salt: 1.6,
    isDrink: false,
    isAlcohol: false,
  },
  {
    id: 303,
    name: "みたれ（もも肉）",
    category: "たれ焼",
    imageUrl: "https://torikizoku.co.jp/assets/uploads/2023/05/tare_mi.jpg",
    calories: 146,
    salt: 1.1,
    isDrink: false,
    isAlcohol: false,
  },
  {
    id: 304,
    name: "きも（レバー）",
    category: "たれ焼",
    imageUrl: "https://torikizoku.co.jp/assets/uploads/2023/05/tare_kimo.jpg",
    calories: 77,
    salt: 1.2,
    isDrink: false,
    isAlcohol: false,
  },
  {
    id: 305,
    name: "つくねチーズ焼",
    category: "たれ焼",
    imageUrl:
      "https://torikizoku.co.jp/assets/uploads/2023/05/tare_tsukunecheese.jpg",
    calories: 212,
    salt: 1.8,
    isDrink: false,
    isAlcohol: false,
  },
  {
    id: 306,
    name: "つくねたれ",
    category: "たれ焼",
    imageUrl:
      "https://torikizoku.co.jp/assets/uploads/2023/05/tare_tsukune.jpg",
    calories: 171,
    salt: 2,
    isDrink: false,
    isAlcohol: false,
  },
  {
    id: 307,
    name: "かわたれ",
    category: "たれ焼",
    imageUrl: "https://torikizoku.co.jp/assets/uploads/2023/05/tare_kawa.jpg",
    calories: 390,
    salt: 2.4,
    isDrink: false,
    isAlcohol: false,
  },
  {
    id: 308,
    name: "ハート（ハツ）たれ",
    category: "たれ焼",
    imageUrl: "https://torikizoku.co.jp/assets/uploads/2023/05/tare_heart.jpg",
    calories: 111,
    salt: 0.6,
    isDrink: false,
    isAlcohol: false,
  },
  {
    id: 401,
    name: "きも焼 -塩ごま油添え-",
    category: "串焼き",
    imageUrl:
      "https://torikizoku.co.jp/assets/uploads/2023/05/kushi_kimo_shiogomaabura.jpg",
    calories: 208,
    salt: 5.6,
    isDrink: false,
    isAlcohol: false,
  },
  {
    id: 402,
    name: "ピーマン肉詰 -ポン酢味-",
    category: "串焼き",
    imageUrl: "https://torikizoku.co.jp/assets/uploads/2023/05/kushi_piman.jpg",
    calories: 76,
    salt: 1.3,
    isDrink: false,
    isAlcohol: false,
  },
  {
    id: 403,
    name: "むね明太マヨ焼",
    category: "串焼き",
    imageUrl:
      "https://torikizoku.co.jp/assets/uploads/2023/05/kushi_munementai.jpg",
    calories: 131,
    salt: 0.9,
    isDrink: false,
    isAlcohol: false,
  },
  {
    id: 404,
    name: "もちもちチーズ焼",
    category: "串焼き",
    imageUrl:
      "https://torikizoku.co.jp/assets/uploads/2023/05/kushi_mochicheese.jpg",
    calories: 119,
    salt: 0.5,
    isDrink: false,
    isAlcohol: false,
  },
  {
    id: 405,
    name: "牛串焼 -果実とにんにくの旨味-",
    category: "串焼き",
    imageUrl: "https://torikizoku.co.jp/assets/uploads/2023/05/kushi_gyu.jpg",
    calories: 127,
    salt: 0.8,
    isDrink: false,
    isAlcohol: false,
  },
  {
    id: 406,
    name: "豚バラ串焼",
    category: "串焼き",
    imageUrl:
      "https://torikizoku.co.jp/assets/uploads/2023/05/kushi_butabara.jpg",
    calories: 166,
    salt: 0.4,
    isDrink: false,
    isAlcohol: false,
  },
  {
    id: 501,
    name: "トリキのチャンジャ",
    category: "スピードメニュー",
    imageUrl: "https://torikizoku.co.jp/assets/uploads/2023/08/chanja.jpg",
    calories: 27,
    salt: 1.3,
    isDrink: false,
    isAlcohol: false,
  },
  {
    id: 502,
    name: "北海道産 蛸わさび",
    category: "スピードメニュー",
    imageUrl: "https://torikizoku.co.jp/assets/uploads/2023/08/takowasa.jpg",
    calories: 50,
    salt: 1.5,
    isDrink: false,
    isAlcohol: false,
  },
  {
    id: 503,
    name: "味付煮玉子",
    category: "スピードメニュー",
    imageUrl: "https://torikizoku.co.jp/assets/uploads/2023/08/nitamago.jpg",
    calories: 157,
    salt: 2.2,
    isDrink: false,
    isAlcohol: false,
  },
  {
    id: 504,
    name: "親鶏炙り焼マヨサラダ",
    category: "スピードメニュー",
    imageUrl:
      "https://torikizoku.co.jp/assets/uploads/2023/05/oyadori_aburimayo.jpg",
    calories: 182,
    salt: 1.1,
    isDrink: false,
    isAlcohol: false,
  },
  {
    id: 505,
    name: "超！白ねぎ塩こんぶ",
    category: "スピードメニュー",
    imageUrl:
      "https://torikizoku.co.jp/assets/uploads/2023/05/shironegi_shiokonbu.jpg",
    calories: 90,
    salt: 1.5,
    isDrink: false,
    isAlcohol: false,
  },
  {
    id: 506,
    name: "ホルモンねぎ盛ポン酢",
    category: "スピードメニュー",
    imageUrl: "https://torikizoku.co.jp/assets/uploads/2023/05/hormone.jpg",
    calories: 98,
    salt: 1.1,
    isDrink: false,
    isAlcohol: false,
  },
  {
    id: 507,
    name: "国産枝豆",
    category: "スピードメニュー",
    imageUrl: "https://torikizoku.co.jp/assets/uploads/2023/05/edamame.jpg",
    calories: 125,
    salt: 0.6,
    isDrink: false,
    isAlcohol: false,
  },
  {
    id: 508,
    name: "キャベツ盛",
    category: "スピードメニュー",
    imageUrl: "https://torikizoku.co.jp/assets/uploads/2023/05/cabbagemori.jpg",
    calories: 36,
    salt: 3,
    isDrink: false,
    isAlcohol: false,
  },
  {
    id: 509,
    name: "塩だれキューリ",
    category: "スピードメニュー",
    imageUrl:
      "https://torikizoku.co.jp/assets/uploads/2023/05/shiodare_kyuri.jpg",
    calories: 52,
    salt: 2.4,
    isDrink: false,
    isAlcohol: false,
  },
  {
    id: 510,
    name: "冷やしトマト",
    category: "スピードメニュー",
    imageUrl:
      "https://torikizoku.co.jp/assets/uploads/2024/02/hiyashi_tomato.jpg",
    calories: 66,
    salt: 0.1,
    isDrink: false,
    isAlcohol: false,
  },
  {
    id: 601,
    name: "トリキの唐揚",
    category: "逸品料理",
    imageUrl: "https://torikizoku.co.jp/assets/uploads/2023/05/karaage.jpg",
    calories: 322,
    salt: 3.4,
    isDrink: false,
    isAlcohol: false,
  },
  {
    id: 602,
    name: "ふんわり山芋の鉄板焼",
    category: "逸品料理",
    imageUrl:
      "https://torikizoku.co.jp/assets/uploads/2023/05/yamaimo_teppan.jpg",
    calories: 128,
    salt: 1.8,
    isDrink: false,
    isAlcohol: false,
  },
  {
    id: 603,
    name: "和風とりポテトサラダ",
    category: "逸品料理",
    imageUrl:
      "https://torikizoku.co.jp/assets/uploads/2024/02/wafu_toripotato_sarada.jpg",
    calories: 335,
    salt: 2.3,
    isDrink: false,
    isAlcohol: false,
  },
  {
    id: 604,
    name: "北海道 海と大地のポテトサラダ",
    category: "逸品料理",
    imageUrl:
      "https://torikizoku.co.jp/assets/uploads/2023/05/potato_sarada.jpg",
    calories: 378,
    salt: 2.6,
    isDrink: false,
    isAlcohol: false,
  },
  {
    id: 605,
    name: "ポテトフライ",
    category: "逸品料理",
    imageUrl:
      "https://torikizoku.co.jp/assets/uploads/2023/08/french-fries.jpg",
    calories: 359,
    salt: 0.7,
    isDrink: false,
    isAlcohol: false,
  },
  {
    id: 606,
    name: "チキン南蛮",
    category: "逸品料理",
    imageUrl:
      "https://torikizoku.co.jp/assets/uploads/2023/05/chicken_namban.jpg",
    calories: 490,
    salt: 2.2,
    isDrink: false,
    isAlcohol: false,
  },
  {
    id: 607,
    name: "とり天 -梅肉ソース添え-",
    category: "逸品料理",
    imageUrl: "https://torikizoku.co.jp/assets/uploads/2023/05/toriten.jpg",
    calories: 306,
    salt: 2,
    isDrink: false,
    isAlcohol: false,
  },
  {
    id: 608,
    name: "カマンベールコロッケ",
    category: "逸品料理",
    imageUrl:
      "https://torikizoku.co.jp/assets/uploads/2023/05/camembert_croquette.jpg",
    calories: 257,
    salt: 1.9,
    isDrink: false,
    isAlcohol: false,
  },
  {
    id: 609,
    name: "ひざなんこつ唐揚",
    category: "逸品料理",
    imageUrl:
      "https://torikizoku.co.jp/assets/uploads/2023/05/nankotsu_karaage.jpg",
    calories: 168,
    salt: 1.9,
    isDrink: false,
    isAlcohol: false,
  },
  {
    id: 610,
    name: "鶏皮チップ",
    category: "逸品料理",
    imageUrl: "https://torikizoku.co.jp/assets/uploads/2023/05/torikawa.jpg",
    calories: 380,
    salt: 1.2,
    isDrink: false,
    isAlcohol: false,
  },
  {
    id: 701,
    name: "とり釜飯",
    category: "ご飯もの",
    imageUrl:
      "https://torikizoku.co.jp/assets/uploads/2023/05/torikamameshi.jpg",
    calories: 416,
    salt: 3.6,
    isDrink: false,
    isAlcohol: false,
  },
  {
    id: 702,
    name: "とり白湯めん",
    category: "ご飯もの",
    imageUrl: "https://torikizoku.co.jp/assets/uploads/2023/08/toripaitan.jpg",
    calories: 251,
    salt: 7.3,
    isDrink: false,
    isAlcohol: false,
  },
  {
    id: 703,
    name: "とり雑炊",
    category: "ご飯もの",
    imageUrl: "https://torikizoku.co.jp/assets/uploads/2023/05/torizousui.jpg",
    calories: 239,
    salt: 5.4,
    isDrink: false,
    isAlcohol: false,
  },
  {
    id: 704,
    name: "鶏スパイス丼 -バター醤油風味-",
    category: "ご飯もの",
    imageUrl:
      "https://torikizoku.co.jp/assets/uploads/2023/05/tori_spice_don.jpg",
    calories: 383,
    salt: 3.5,
    isDrink: false,
    isAlcohol: false,
  },
  {
    id: 705,
    name: "ご飯セット -温玉添え-",
    category: "ご飯もの",
    imageUrl: "https://torikizoku.co.jp/assets/uploads/2023/05/rice_set.jpg",
    calories: 526,
    salt: 3.1,
    isDrink: false,
    isAlcohol: false,
  },
  {
    id: 801,
    name: "鳥貴ドームアイス ～いちご～",
    category: "デザート",
    imageUrl:
      "https://torikizoku.co.jp/assets/uploads/2024/02/toriki_domu_ice_ichigo.jpg",
    calories: 224,
    salt: 0.1,
    isDrink: false,
    isAlcohol: false,
  },
  {
    id: 802,
    name: "鳥貴ドームアイス ～みたらし～",
    category: "デザート",
    imageUrl:
      "https://torikizoku.co.jp/assets/uploads/2024/02/toriki_domu_ice_mitarashi.jpg",
    calories: 218,
    salt: 0.3,
    isDrink: false,
    isAlcohol: false,
  },
  {
    id: 803,
    name: "魅惑のチョコレートみるく",
    category: "デザート",
    imageUrl:
      "https://torikizoku.co.jp/assets/uploads/2023/08/chocolate-milk.jpg",
    calories: 326,
    salt: 0.4,
    isDrink: false,
    isAlcohol: false,
  },
  {
    id: 804,
    name: "チョコパフェ -チュロ添え-",
    category: "デザート",
    imageUrl:
      "https://torikizoku.co.jp/assets/uploads/2023/05/choco_parfait.jpg",
    calories: 287,
    salt: 0.3,
    isDrink: false,
    isAlcohol: false,
  },
  {
    id: 805,
    name: "カタラーナアイス",
    category: "デザート",
    imageUrl:
      "https://torikizoku.co.jp/assets/uploads/2023/05/catalana_ice_cream.jpg",
    calories: 238,
    salt: 0.1,
    isDrink: false,
    isAlcohol: false,
  },
  {
    id: 2101,
    name: "ザ・プレミアム・モルツ",
    category: "ビール",
    imageUrl: "",
    calories: 120,
    isDrink: true,
    isAlcohol: true,
  },
  {
    id: 2201,
    name: "メガレモンサワー",
    category: "メガ",
    imageUrl: "",
    calories: 116,
    isDrink: true,
    isAlcohol: true,
  },
  {
    id: 2202,
    name: "メガハイボール（ジムビーム）",
    category: "メガ",
    imageUrl: "",
    calories: 135,
    isDrink: true,
    isAlcohol: true,
  },
  {
    id: 2203,
    name: "メガ金麦 ※ビール系飲料",
    category: "メガ",
    imageUrl: "",
    calories: 249,
    isDrink: true,
    isAlcohol: true,
  },
  {
    id: 2301,
    name: "男梅サワー",
    category: "チューハイ",
    imageUrl: "",
    calories: 94,
    isDrink: true,
    isAlcohol: true,
  },
  {
    id: 2302,
    name: "カルピスチューハイ",
    category: "チューハイ",
    imageUrl: "",
    calories: 205,
    isDrink: true,
    isAlcohol: true,
  },
  {
    id: 2401,
    name: "優しいレモンサワー",
    category: "レモンサワー",
    imageUrl: "",
    calories: 85,
    isDrink: true,
    isAlcohol: true,
  },
  {
    id: 2402,
    name: "こだわり酒場のレモンサワー",
    category: "レモンサワー",
    imageUrl: "",
    calories: 72,
    isDrink: true,
    isAlcohol: true,
  },
  {
    id: 2601,
    name: "角ハイボール",
    category: "ハイボール",
    imageUrl: "",
    calories: 70,
    isDrink: true,
    isAlcohol: true,
  },
  {
    id: 2602,
    name: "知多ハイボール",
    category: "ハイボール",
    imageUrl: "",
    calories: 68,
    isDrink: true,
    isAlcohol: true,
  },
  {
    id: 2603,
    name: "コーラハイ",
    category: "ハイボール",
    imageUrl: "",
    calories: 129,
    isDrink: true,
    isAlcohol: true,
  },
  {
    id: 2604,
    name: "ジンジャーハイ",
    category: "ハイボール",
    imageUrl: "",
    calories: 119,
    isDrink: true,
    isAlcohol: true,
  },
  {
    id: 2701,
    name: "緑茶ハイ",
    category: "お茶ハイ",
    imageUrl: "",
    calories: 67,
    isDrink: true,
    isAlcohol: true,
  },
  {
    id: 2702,
    name: "ウーロンハイ",
    category: "お茶ハイ",
    imageUrl: "",
    calories: 65,
    isDrink: true,
    isAlcohol: true,
  },
  {
    id: 2801,
    name: "翠ジンソーダ",
    category: "国産ジン",
    imageUrl: "",
    calories: 68,
    isDrink: true,
    isAlcohol: true,
  },
  {
    id: 2802,
    name: "翠ジントニック",
    category: "国産ジン",
    imageUrl: "",
    calories: 113,
    isDrink: true,
    isAlcohol: true,
  },
  {
    id: 2803,
    name: "翠ジンオレンジ",
    category: "国産ジン",
    imageUrl: "",
    calories: 127,
    isDrink: true,
    isAlcohol: true,
  },
  {
    id: 2804,
    name: "翠ジンジンジャーエール",
    category: "国産ジン",
    imageUrl: "",
    calories: 120,
    isDrink: true,
    isAlcohol: true,
  },
  {
    id: 2805,
    name: "翠ジンコーラ",
    category: "国産ジン",
    imageUrl: "",
    calories: 130,
    isDrink: true,
    isAlcohol: true,
  },
  {
    id: 2901,
    name: "優しいカシスミルク割",
    category: "カクテル",
    imageUrl: "",
    calories: 150,
    isDrink: true,
    isAlcohol: true,
  },
  {
    id: 2902,
    name: "優しいカシスオレンジ割",
    category: "カクテル",
    imageUrl: "",
    calories: 132,
    isDrink: true,
    isAlcohol: true,
  },
  {
    id: 2903,
    name: "優しいレモンとカシス",
    category: "カクテル",
    imageUrl: "",
    calories: 140,
    isDrink: true,
    isAlcohol: true,
  },
  {
    id: 3001,
    name: "優しいみかんのお酒オレンジ割",
    category: "果実酒",
    imageUrl: "",
    calories: 117,
    isDrink: true,
    isAlcohol: true,
  },
  {
    id: 3101,
    name: "トリキホワイト",
    category: "ワイン",
    imageUrl: "",
    calories: 131,
    isDrink: true,
    isAlcohol: true,
  },
  {
    id: 3102,
    name: "トリキレッド",
    category: "ワイン",
    imageUrl: "",
    calories: 122,
    isDrink: true,
    isAlcohol: true,
  },
  {
    id: 3201,
    name: "大隅焼酎ソーダ",
    category: "焼酎",
    imageUrl: "",
    calories: 129,
    isDrink: true,
    isAlcohol: true,
  },
  {
    id: 3202,
    name: "大隅（麦）",
    category: "焼酎",
    imageUrl: "",
    calories: 129,
    isDrink: true,
    isAlcohol: true,
  },
  {
    id: 3203,
    name: "黒霧島（芋）",
    category: "焼酎",
    imageUrl: "",
    calories: 128,
    isDrink: true,
    isAlcohol: true,
  },
  {
    id: 3301,
    name: "松竹梅 豪快 純米酒＜カップ酒＞",
    category: "日本酒",
    imageUrl: "",
    calories: 181,
    isDrink: true,
    isAlcohol: true,
  },
  {
    id: 3401,
    name: "紀州の南高梅酒",
    category: "梅酒",
    imageUrl: "",
    calories: 157,
    isDrink: true,
    isAlcohol: true,
  },
  {
    id: 3501,
    name: "オールフリー",
    category: "ノンアルコール",
    imageUrl: "",
    calories: 0,
    isDrink: true,
    isAlcohol: false,
  },
  {
    id: 4101,
    name: "ウーロン茶",
    category: "ソフトドリンク",
    imageUrl: "",
    calories: 2,
    isDrink: true,
    isAlcohol: false,
  },
  {
    id: 4102,
    name: "オレンジジュース",
    category: "ソフトドリンク",
    imageUrl: "",
    calories: 107,
    isDrink: true,
    isAlcohol: false,
  },
  {
    id: 4103,
    name: "ジンジャーエール",
    category: "ソフトドリンク",
    imageUrl: "",
    calories: 94,
    isDrink: true,
    isAlcohol: false,
  },
  {
    id: 4104,
    name: "レモネード",
    category: "ソフトドリンク",
    imageUrl: "",
    calories: 121,
    isDrink: true,
    isAlcohol: false,
  },
  {
    id: 4105,
    name: "レモンスカッシュ",
    category: "ソフトドリンク",
    imageUrl: "",
    calories: 121,
    isDrink: true,
    isAlcohol: false,
  },
  {
    id: 4106,
    name: "コーラ",
    category: "ソフトドリンク",
    imageUrl: "",
    calories: 113,
    isDrink: true,
    isAlcohol: false,
  },
  {
    id: 4107,
    name: "カルピスウォーター",
    category: "ソフトドリンク",
    imageUrl: "",
    calories: 211,
    isDrink: true,
    isAlcohol: false,
  },
  {
    id: 4108,
    name: "ホットウーロン茶",
    category: "ソフトドリンク",
    imageUrl: "",
    calories: 2,
    isDrink: true,
    isAlcohol: false,
  },
  {
    id: 4201,
    name: "ミックスジュース",
    category: "クラフトジュース",
    imageUrl: "",
    calories: 219,
    isDrink: true,
    isAlcohol: false,
  },
  {
    id: 4202,
    name: "大人のホットジンジャー",
    category: "クラフトジュース",
    imageUrl: "",
    calories: 141,
    isDrink: true,
    isAlcohol: false,
  },
  {
    id: 4203,
    name: "大人のジンジャーソーダ",
    category: "クラフトジュース",
    imageUrl: "",
    calories: 141,
    isDrink: true,
    isAlcohol: false,
  },
  {
    id: 4204,
    name: "やさしい苺とミルク",
    category: "クラフトジュース",
    imageUrl: "",
    calories: 164,
    isDrink: true,
    isAlcohol: false,
  },
  {
    id: 4301,
    name: "アイスコーヒー",
    category: "コーヒー",
    imageUrl: "",
    calories: 47,
    isDrink: true,
    isAlcohol: false,
  },
  {
    id: 4302,
    name: "ホットコーヒー",
    category: "コーヒー",
    imageUrl: "",
    calories: 39,
    isDrink: true,
    isAlcohol: false,
  },
  {
    id: 9901,
    name: "抜刀唐揚 ～紅生姜編～",
    category: "数量限定",
    imageUrl:
      "https://torikizoku.co.jp/assets/uploads/2024/07/karaagre_benishouga.jpg",
    calories: 362,
    salt: 2.2,
    isDrink: false,
    isAlcohol: false,
  },
  {
    id: 9902,
    name: "ちからこぶの黒胡椒串焼",
    category: "数量限定",
    imageUrl:
      "https://torikizoku.co.jp/assets/uploads/2024/07/tikarakobu_kurokoshou.jpg",
    calories: 211,
    salt: 2.3,
    isDrink: false,
    isAlcohol: false,
  },
  {
    id: 9903,
    name: "デカい塩むすび ～鮭梅のせ～",
    category: "数量限定",
    imageUrl:
      "https://torikizoku.co.jp/assets/uploads/2024/07/dekaisiomusubi.jpg",
    calories: 534,
    salt: 4.1,
    isDrink: false,
    isAlcohol: false,
  },
  {
    id: 9904,
    name: "大隅和のチューハイ",
    category: "数量限定",
    imageUrl:
      "https://torikizoku.co.jp/assets/uploads/2024/07/osumiwanochuhai.jpg",
    calories: 73,
    isDrink: true,
    isAlcohol: true,
  },
  {
    id: 9905,
    name: "ザクロベリーソーダ",
    category: "数量限定",
    imageUrl:
      "https://torikizoku.co.jp/assets/uploads/2024/07/zakuroberrysoda.jpg",
    calories: 156,
    isDrink: true,
    isAlcohol: false,
  },
];
